service: use-reducer-login-database

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  usersTableName: ${self:custom.stage}-users
  socketConnectionsTableName: ${self:custom.stage}-socketConnections

provider:
  name: aws
  stage: dev
  region: us-west-2

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.usersTableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: N
          - AttributeName: updatedAt
            AttributeType: N
          - AttributeName: globalSort
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: users_globalSort_createdAt_gsi
            KeySchema:
              - AttributeName: globalSort
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: users_globalSort_updatedAt_gsi
            KeySchema:
              - AttributeName: globalSort
                KeyType: HASH
              - AttributeName: updatedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: users_email_gsi
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST
        # StreamSpecification:
        #   StreamViewType: NEW_AND_OLD_IMAGES
    SocketConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.socketConnectionsTableName}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

  Outputs:
    usersTableArn:
      Value:
        Fn::GetAtt:
          - usersTable
          - Arn
      Export:
        Name: ${self:custom.stage}-usersTableArn
    SocketConnectionsTableArn:
      Value:
        Fn::GetAtt:
          - SocketConnectionsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-SocketConnectionsTableArn
